# Generated by Django 2.2.3 on 2020-02-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200204_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slugs',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
