# Generated by Django 2.2.3 on 2020-02-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200205_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slugs',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
